name: Auto cancel
on: pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # 동일 그룹의 워크플로우가 실행 중이면 취소
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 120
