name: Intermediate environment variables
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      ACTOR: ${{ github.actor }} # 컨텍스트 값(github.actor)을 환경 변수로 설정
    steps:
      - run: echo "${ACTOR}"     # 환경 변수를 통해 컨텍스트 값 참조
